SELECT name, database_id, create_date  
FROM sys.databases ; 

USE VIVEVOLARDB;

SELECT * FROM information_schema.columns WHERE table_name = 'dbo.PAISES'

SELECT i.name AS index_name
    ,i.type_desc
    ,is_unique
    ,ds.type_desc AS filegroup_or_partition_scheme
    ,ds.name AS filegroup_or_partition_scheme_name
    ,ignore_dup_key
    ,is_primary_key
    ,is_unique_constraint
    ,fill_factor
    ,is_padded
    ,is_disabled
    ,allow_row_locks
    ,allow_page_locks
FROM sys.indexes AS i
INNER JOIN sys.data_spaces AS ds ON i.data_space_id = ds.data_space_id
WHERE is_hypothetical = 0 AND i.index_id <> 0 
AND i.object_id = OBJECT_ID('dbo.aeropuertos');

SELECT * FROM DBO.PAISES;

INSERT INTO DBO.PAISES(NOMBRE, HABILITADO) VALUES ('COLOMBIA','S');

SELECT * FROM DBO.ESTADOS

INSERT INTO DBO.ESTADOS(NOMBRE, IDPAIS, HABILITADO) VALUES ('ANTIOQUIA', 1, 'S');
INSERT INTO DBO.ESTADOS(NOMBRE, IDPAIS, HABILITADO) VALUES ('CUNDINAMARCA', 1, 'S');
INSERT INTO DBO.ESTADOS(NOMBRE, IDPAIS, HABILITADO) VALUES ('BOLIVAR', 1, 'S');
INSERT INTO DBO.ESTADOS(NOMBRE, IDPAIS, HABILITADO) VALUES ('MAGDALENA', 1, 'S');
INSERT INTO DBO.ESTADOS(NOMBRE, IDPAIS, HABILITADO) VALUES ('SAN ANDRES Y PROVIDENCIA', 1, 'S');
INSERT INTO DBO.ESTADOS(NOMBRE, IDPAIS, HABILITADO) VALUES ('AMAZONAS', 1, 'S');
INSERT INTO DBO.ESTADOS(NOMBRE, IDPAIS, HABILITADO) VALUES ('ATLANTICO', 1, 'S');
INSERT INTO DBO.ESTADOS(NOMBRE, IDPAIS, HABILITADO) VALUES ('NARIÑO', 1, 'S');

SELECT * FROM DBO.CIUDADES;

INSERT INTO DBO.CIUDADES(NOMBRE, IDESTADO, HABILITADO) VALUES ('MEDELLIN', 1, 'S');
INSERT INTO DBO.CIUDADES(NOMBRE, IDESTADO, HABILITADO) VALUES ('BOGOTA', 2, 'S');
INSERT INTO DBO.CIUDADES(NOMBRE, IDESTADO, HABILITADO) VALUES ('CARTAGENA', 3, 'S');
INSERT INTO DBO.CIUDADES(NOMBRE, IDESTADO, HABILITADO) VALUES ('SANTA MARTA', 4, 'S');
INSERT INTO DBO.CIUDADES(NOMBRE, IDESTADO, HABILITADO) VALUES ('SAN ANDRES', 5, 'S');
INSERT INTO DBO.CIUDADES(NOMBRE, IDESTADO, HABILITADO) VALUES ('LETICIA', 6, 'S');
INSERT INTO DBO.CIUDADES(NOMBRE, IDESTADO, HABILITADO) VALUES ('BARRANQUILLA', 7, 'S');
INSERT INTO DBO.CIUDADES(NOMBRE, IDESTADO, HABILITADO) VALUES ('PASTO', 8, 'S');
INSERT INTO DBO.CIUDADES(NOMBRE, IDESTADO, HABILITADO) VALUES ('IPIALES', 8, 'S');

EXEC sp_rename 'DBO.AEROPUESTOS', 'AEROPUERTOS';  

SELECT * FROM DBO.AEROPUERTOS

INSERT INTO DBO.AEROPUERTOS(CODIGOMUNDIAL, NOMBRE, IDCIUDAD, HABILITADO) VALUES ('MDE','AEROPUERTO INTERNACIONAL JOSE MARIA CORDOBA', 1, 'S');
INSERT INTO DBO.AEROPUERTOS(CODIGOMUNDIAL, NOMBRE, IDCIUDAD, HABILITADO) VALUES ('BOG','AEROPUERTO INTERNACIONAL EL DORADO', 2, 'S');
INSERT INTO DBO.AEROPUERTOS(CODIGOMUNDIAL, NOMBRE, IDCIUDAD, HABILITADO) VALUES ('CTG','AEROPUERTO INTERNACIONAL RAFAEL NUÑEZ', 3, 'S');
INSERT INTO DBO.AEROPUERTOS(CODIGOMUNDIAL, NOMBRE, IDCIUDAD, HABILITADO) VALUES ('SMR','AEROPUERTO INTERNACIONAL SIMON BOLIVAR', 4, 'S');
INSERT INTO DBO.AEROPUERTOS(CODIGOMUNDIAL, NOMBRE, IDCIUDAD, HABILITADO) VALUES ('ADZ','AEROPUERTO INTERNACIONAL GUSTAVO ROJAS PINILLA', 5, 'S');
INSERT INTO DBO.AEROPUERTOS(CODIGOMUNDIAL, NOMBRE, IDCIUDAD, HABILITADO) VALUES ('LET','AEROPUERTO INTERNACIONAL ALFREDO VASQUEZ COBO', 6, 'S');
INSERT INTO DBO.AEROPUERTOS(CODIGOMUNDIAL, NOMBRE, IDCIUDAD, HABILITADO) VALUES ('BAQ','AEROPUERTO INTERNACIONAL ERNESTO CORTISSOZ', 7, 'S');
INSERT INTO DBO.AEROPUERTOS(CODIGOMUNDIAL, NOMBRE, IDCIUDAD, HABILITADO) VALUES ('PSO','AEROPUERTO ANTONIO NARIÑO', 8, 'S');
INSERT INTO DBO.AEROPUERTOS(CODIGOMUNDIAL, NOMBRE, IDCIUDAD, HABILITADO) VALUES ('IPI','AEROPUERTO SAN LUIS', 9, 'S');

SELECT * FROM ORIGENESDESTINOS;

INSERT INTO DBO.ORIGENESDESTINOS(IDAEROPUERTO, NOMBRE, ESORIGEN, ESDESTINO, HABILITADO) VALUES (1,'MEDELLIN/RIONEGRO','S','S','S');
INSERT INTO DBO.ORIGENESDESTINOS(ID,IDAEROPUERTO, NOMBRE, ESORIGEN, ESDESTINO, HABILITADO) VALUES (1,2,'BOGOTA DC','S','S','S');
INSERT INTO DBO.ORIGENESDESTINOS(IDAEROPUERTO, NOMBRE, ESORIGEN, ESDESTINO, HABILITADO) VALUES (7,'BARRANQUILLA/SOLEDAD','S','S','S');

